let b:ide_goto_definition = 'OmniSharp#GotoDefinition'
let b:ide_open_documentation = 'OmniSharp#TypeLookupWithDocumentation'
let b:ide_rename_symbol = 'OmniSharp#Rename'
let b:ide_fzf_list_symbols = 'OmniSharp#FindSymbol'
let b:ide_fzf_list_references = 'OmniSharp#FindUsages'
